services:
    web1:
        build:
            context: ..
            dockerfile: Dockerfile
        hostname: web1
        restart: on-failure
        environment:
            PING_LISTEN_PORT: 3030
        networks:
            front:

    web2:
        build:
            context: ..
            dockerfile: Dockerfile
        hostname: web2
        restart: on-failure
        environment:
            PING_LISTEN_PORT: 3030
        networks:
            front:

    web3:
        build:
            context: ..
            dockerfile: Dockerfile
        hostname: web3
        restart: on-failure
        environment:
            PING_LISTEN_PORT: 3030
        networks:
            front:

    web4:
        build:
            context: ..
            dockerfile: Dockerfile
        hostname: web4
        restart: on-failure
        environment:
            PING_LISTEN_PORT: 3030
        networks:
            front:

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        restart: on-failure
        networks:
            front:

networks:
    front:
        driver: bridge
