services:
    web:
        build:
            context: ..
            dockerfile: Dockerfile
        restart: on-failure
        environment:
            PING_LISTEN_PORT: 3030
        networks:
            front:
        deploy:
            replicas: 4

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        restart: on-failure
        networks:
            front:
        depends_on:
            -   web

networks:
    front:
        driver: bridge
