services:
    wordpress:
        image: wordpress:latest
        deploy:
            replicas: 2
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpresspassword
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_REDIS_HOST', 'redis');
                define('WP_CACHE', true);
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - backend
            - frontend

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpresspassword
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

    redis:
        image: redis:latest
        networks:
            - backend

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - wordpress

volumes:
    wordpress_data:
    mysql_data:

networks:
    backend:
    frontend: